# App name
spring.application.name=payment-service

# Port
server.port=8084

# MongoDB connection
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ecommerce_payments

# Swagger UI path
springdoc.swagger-ui.path=/swagger-ui.html